config/routes.rb
Rails.application.routes.draw do
  resources :posts, :memos, except: [:show] do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :title, length: {minimum: 1}
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: %i[destroy edit update]
  def index
    @memos = Memo.all.order(created_at: :desc)
  end

  def new
  end
  
  def create
    @memo = Memo.create!(memo_params)
  end

  def destroy
    @memo.destroy!
  end

  def edit
  end

  def update
    @memo.update!(memo_params)
  end
  
  private
  def memo_params
    params.require(:memo).permit(:title, :name)
  end

  def set_memo
    @memo = Memo.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[destroy edit update]
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
  end

  def create
    @post = Post.create!(post_params)
    render @posts
  end

  def destroy
    @post.destroy!
  end

  def edit
  end

  def update
    @post.update!(post_params)
  end

  private
  def post_params
    params.require(:post).permit(:title, :name, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/27743ad700.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="full-page">
    <header>
      <div class="container">
        <div class="title">BOOKLIST</div>
        <!--新規追加ボタン-->
        <div class="add-box">
          <a class="add-btn" id="add-btn" href="#add-form"><i class="fas fa-plus"></i>ADD</a>
        </div>
      </div>
    </header>
    <div class="nav">
      <ul class="nav-list">
        <li>
          <%= link_to "PHRASE", "/posts" %>
        </li>
        <li>
          <%= link_to "BOOKLIST", "/memos" %>
        </li>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>

app/views/memos/_create.html.erb
<%= form_with model: memo, class: "form", id: "form", local: false do |f| %>
  <div class="form-body" id="edit">
    <%= f.text_field :title, placeholder: "Title" %>
    <%= f.text_field :name, placeholder: "Author" %>
    <%= f.submit value %>
  </div>
<% end %>

app/views/memos/_memo.html.erb
<div class="memos-index-item index-item" id="<%= memo.id %>">
  <div class="action-btn">
    <%= link_to(edit_memo_path(memo), class: "edit-btn", remote: true) do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to(memo_path(memo), class: "delete-btn", method: :delete, remote: true) do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </div>
  <p><%= memo.title %></p>
  <div class="book-info">
    <small><%= memo.name %></small>
  </div>
  <div class="book-when">
    <small class="created_at"><%= memo.created_at.to_s(:datetime_jp) %></small>
  </div>
</div>

app/views/memos/create.js.erb
document.getElementById('memos-index').insertAdjacentHTML('afterbegin', '<%= j(render @memo) %>');
document.getElementById('memo_title').value = '';
document.getElementById('memo_name').value = '';
var new_memo = document.getElementById('<%= @memo.id %>');
window.scrollTo(0, new_memo);

app/views/memos/destroy.js.erb
document.getElementById('<%= @memo.id %>').outerHTML = '';
document.getElementById('data.id').outerHTML = '';  

app/views/memos/edit.js.erb
var form = document.getElementsByTagName('form')[0];
form.outerHTML = '<%= j(render 'create', memo: @memo, value: 'update') %>';
window.scrollTo(0, 700);

app/views/memos/index.html.erb
<div class="box">
<!--投稿詳細ページ-->
  <div class="memos-index index" id="memos-index">
    <%= render @memos %>
  </div>

<!-- 新規投稿フォーム --> 
  <div class="add-form" id="add-form">
  <%= render 'create', memo: Memo.new, value: 'submit' %>
  </div>
</div>
  

app/views/memos/update.js.erb
// 対応するメッセージを更新
document.getElementById('<%= @memo.id %>').outerHTML = '<%= j(render @memo) %>';

var new_memo = document.getElementById('<%= @memo.id %>');
window.scrollTo(0, new_memo);

// フォームを新規投稿フォームに戻す
var form = document.getElementsByTagName('form')[0];
form.outerHTML = '<%= j(render 'create', memo: Memo.new, value: 'submit') %>';

app/views/posts/_create.html.erb
<%= form_with model: post, class: "form", id: "form", local: false do |f| %>
  <div class="form-body">
    <%= f.text_field :content, placeholder: "PHRASE" %> 
    <%= f.text_field :tilte, placeholder: "TITLE" %>
    <%= f.text_field :name, placeholder: "AUTHOR" %>
    <%= f.submit value, id: "submit-button"%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="posts-index-item index-item" id="<%= post.id %>">
  <div class="action-btn">
    <%= link_to(edit_post_path(post), class: "edit-btn", remote: true) do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to(post_path(post), class: "delete-btn", method: :delete, remote: true) do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </div>
  <p><%= post.content %></p>
  <div class="book-when">
    <small class="created_at"><%= post.created_at.to_s(:datetime_jp) %></small>
  </div>  
  <div class="book-info">
    <small><%= post.title %></small>
    <small><%= post.name %></small>
  </div>
</div>

app/views/posts/create.js.erb
document.getElementById('posts-index').insertAdjacentHTML('afterbegin', '<%= j(render @post) %>');
document.getElementById('post_title').value = '';
document.getElementById('post_name').value = '';
document.getElementById('post_content').value = '';
var new_post = document.getElementById('<%= @post.id %>');
window.scrollTo(0, new_post);

app/views/posts/destroy.js.erb
document.getElementById('<%= @post.id %>').outerHTML = '';
var form = document.getElementsByTagName('form')[0];
form.outerHTML = '<%= j(render 'create', post: Post.new, value: 'submit') %>'

app/views/posts/edit.js.erb
var form = document.getElementsByTagName('form')[0];
form.outerHTML = '<%= j(render 'create', post: @post, value: 'update') %>';
window.scrollTo(0, 700);

app/views/posts/index.html.erb
<div class="box">
  <!--投稿詳細ページ-->
  <div class="posts-index index" id="posts-index">
    <%= render @posts %>
  </div>

  <!-- 新規投稿フォーム -->
  <div class="add-form" id="add-form">
    <%= render 'create', post: Post.new, value: 'ADD' %>
  </div>

</div>
  

app/views/posts/new.js.erb
var form = document.getElementsByTagName('form')[1]
form.outerHTML = '<%= j(render 'form', message: Message.new, value: '投稿') %>'

app/views/posts/update.js.erb
// 対応するメッセージを更新
document.getElementById('<%= @post.id %>').outerHTML = '<%= j(render @post) %>';

//新しい投稿まで移動
var new_post = document.getElementById('<%= @post.id %>')
window.scrollTo(0, new_post);

// フォームを新規投稿フォームに戻す
var form = document.getElementsByTagName('form')[1];
form.outerHTML = '<%= j(render 'create', post: Post.new, value: 'submit') %>'